import { describe, expect, it } from '@jest/globals';
import { TechnicianApi, TechnicianRawRepository, InvalidTechnicianRecord, ServiceTitanTechnicianIngestionService } from '../../src/modules/servicetitan/ingestion/technician.ingestion';
import { CustomerSyncInProgressError } from '../../src/modules/servicetitan/ingestion/customer.ingestion';

class Repo implements TechnicianRawRepository { public records: { id: string; latest: boolean }[] = []; public errors: InvalidTechnicianRecord[] = []; public status = 'RUNNING'; public lockAvailable = true; public lockHeld = false; public lastSynced: Date | null = null; public failMetadata = false;
  public async withExclusiveLock<T>(work: (r: TechnicianRawRepository) => Promise<T>): Promise<T> { if (!this.lockAvailable || this.lockHeld) throw new CustomerSyncInProgressError(); this.lockHeld = true; try { return await work(this); } finally { this.lockHeld = false; } }
  public async recoverInterruptedRuns(): Promise<void> { this.status = 'RECOVERED'; }
  public async createSyncRun(): Promise<string> { return 'tech-run'; }
  public async getContinuation(): Promise<string | null> { return null; }
  public async getLastSyncedAt(): Promise<Date | null> { return this.lastSynced; }
  public async commitBatch(_run: string, rows: { sourceId: string; payload: Record<string, unknown> }[], errors: InvalidTechnicianRecord[]): Promise<void> { for (const row of rows) { this.records.filter((x) => x.id === row.sourceId && x.latest).forEach((x) => { x.latest = false; }); this.records.push({ id: row.sourceId, latest: true }); } this.errors.push(...errors); }
  public async updateContinuation(): Promise<void> { if (this.failMetadata) throw new Error('metadata failure'); this.lastSynced = new Date(); }
  public async completeSyncRun(): Promise<void> { this.status = 'COMPLETED'; }
  public async failSyncRun(): Promise<void> { this.status = 'FAILED'; }
}
class Api implements TechnicianApi { public calls: Array<Record<string, unknown>> = []; public constructor(private readonly responses: unknown[]) {} public async get<T>(_endpoint: string, params?: Record<string, unknown>): Promise<T> { this.calls.push(params ?? {}); const response = this.responses.shift(); if (response instanceof Error) throw response; return response as T; } }

describe('ServiceTitan technician raw ingestion', () => {
  it('paginates from page one until hasMore is false', async () => { const api = new Api([{ page: 1, pageSize: 50, hasMore: true, data: [{ id: 1 }] }, { page: 2, pageSize: 50, hasMore: false, data: [{ id: 2 }] }]); const repo = new Repo(); await new ServiceTitanTechnicianIngestionService(api, repo).run(); expect(api.calls).toEqual([{ page: 1, pageSize: 50 }, { page: 2, pageSize: 50 }]); expect(repo.records).toHaveLength(2); expect(repo.status).toBe('COMPLETED'); });
  it('uses stored last_synced_at as modifiedOnOrAfter for incremental sync', async () => { const repo = new Repo(); repo.lastSynced = new Date('2026-08-26T00:00:00.000Z'); const api = new Api([{ page: 1, pageSize: 50, hasMore: false, data: [{ id: 3 }] }]); await new ServiceTitanTechnicianIngestionService(api, repo).run(); expect(api.calls[0]).toEqual({ page: 1, pageSize: 50, modifiedOnOrAfter: '2026-08-26T00:00:00.000Z' }); });
  it('versions repeated technicians and records malformed payloads', async () => { const repo = new Repo(); await new ServiceTitanTechnicianIngestionService(new Api([{ page: 1, pageSize: 50, hasMore: false, data: [{ id: 7 }, { invalid: true }] }]), repo).run(); await new ServiceTitanTechnicianIngestionService(new Api([{ page: 1, pageSize: 50, hasMore: false, data: [{ id: 7 }] }]), repo).run(); expect(repo.records).toEqual([{ id: '7', latest: false }, { id: '7', latest: true }]); expect(repo.errors).toHaveLength(1); });
  it('marks API and metadata failures and releases the lock', async () => { const repo = new Repo(); await expect(new ServiceTitanTechnicianIngestionService(new Api([new Error('ServiceTitan API Error: [400]')]), repo).run()).rejects.toThrow('technician sync failed'); expect(repo.status).toBe('FAILED'); expect(repo.lockHeld).toBe(false); repo.status = 'RUNNING'; repo.failMetadata = true; await expect(new ServiceTitanTechnicianIngestionService(new Api([{ page: 1, pageSize: 50, hasMore: false, data: [{ id: 8 }] }]), repo).run()).rejects.toThrow('technician sync failed'); });
  it('retries transient failures and rejects lock contention', async () => { const repo = new Repo(); repo.lockAvailable = false; await expect(new ServiceTitanTechnicianIngestionService(new Api([]), repo).run()).rejects.toThrow('already running'); repo.lockAvailable = true; const api = new Api([new Error('[503]'), { page: 1, pageSize: 50, hasMore: false, data: [{ id: 6 }] }]); await new ServiceTitanTechnicianIngestionService(api, repo).run(); expect(api.calls).toHaveLength(2); });
  it('terminates pagination and advances metadata after final persistence', async () => { const repo = new Repo(); const api = new Api([{ page: 1, pageSize: 50, hasMore: false, data: [{ id: 9 }] }]); await new ServiceTitanTechnicianIngestionService(api, repo).run(); expect(repo.lastSynced).toBeInstanceOf(Date); expect(repo.status).toBe('COMPLETED'); });
});
